version: 2.1
jobs:
  lint212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      # - restore_cache:
      #     key: sbt-cache2
      - run: sbt ++2.12.10! check
      # - save_cache:
      #     key: sbt-cache2
      #     paths:
      #       - "~/.cache"
      #       - "~/.sbt"
      #       - "~/.m2"
  lint212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
    steps:
      - checkout
      # - restore_cache:
      #     key: sbt-cache2
      - run: sbt ++2.12.10! check
      # - save_cache:
      #     key: sbt-cache2
      #     paths:
      #       - "~/.cache"
      #       - "~/.sbt"
      #       - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      # - restore_cache:
      #     key: sbt-cache2
      - run: sbt ++2.12.10! test
      # - save_cache:
      #     key: sbt-cache2
      #     paths:
      #       - "~/.cache"
      #       - "~/.sbt"
      #       - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
    steps:
      - checkout
      # - restore_cache:
      #     key: sbt-cache2
      - run: sbt ++2.12.10! test
      # - save_cache:
      #     key: sbt-cache2
      #     paths:
      #       - "~/.cache"
      #       - "~/.sbt"
      #       - "~/.m2"
  release:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache2
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: sbt releaseEarly

workflows:
  version: 2
  build:
    jobs:
      - lint212_jdk8:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - lint212_jdk11:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test212_jdk8:
          requires:
            - lint212_jdk8
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test212_jdk11:
          requires:
            - lint212_jdk11
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test212_jdk11
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
